[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

# Disable Next.js auto-detection
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Pretty URLs configuration
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Redirects for dynamic routes - FIXED
[[redirects]]
  from = "/ancient-wisdom"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/consciousness"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/conspiracy-theories"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/forbidden-science"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/mystical-geography"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/secret-projects"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/ufo-files"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/unexplained-phenomena"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/the-matrix"
  to = "/.netlify/functions/server"
  status = 200

# Article routes
[[redirects]]
  from = "/ancient/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/consciousness/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/conspiracy/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/forbidden/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/mystical/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/secret/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/ufo/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/unexplained/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/matrix/*"
  to = "/.netlify/functions/server"
  status = 200