[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

# Disable Next.js auto-detection
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Pretty URLs configuration
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Redirects for dynamic routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
