[build]
  publish = "."

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Pretty URLs configuration
# This tells Netlify to automatically serve .html files without the extension
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
